---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: drkiq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drkiq
    spec:
      containers:
        - name: drkiq
          image: "localhost:5000/drkiq"
          ports:
            - name: rails
              containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: DATABASE_URL
            - name: WORKER_PROCESSES
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: WORKER_PROCESSES
            - name: LISTEN_ON
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: LISTEN_ON
            - name: SECRET_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: SECRET_TOKEN
            - name: CACHE_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: CACHE_URL
            - name: JOB_WORKER_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JOB_WORKER_URL
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: postgres_password

